author = 'Oxalin'
country_code = 'GB'
description = "Peterborough area, and the East Coast Main Line to Biggleswade"
display_name = 'Peterborough'
doc_files = [ 'Peterborough.md' ]
factual = true
img_files = [ 'Peterborough.bmp' ]
name = 'Peterborough'
release_date = '2022-12-02'
year = 2022
signal_position = "left"
rly_file = 'Peterborough.rly'
ssn_files = [ 'Peterborough Initial Session.ssn']
ttb_files = [ 'Peterborough 29-06-22.ttb' ]
version = '1.0.0'
